nyc_tripdata:
  outputs:
    dev:
      host: "{{ env_var('DBT_DB_HOST') }}"
      dbname: "{{ env_var('DBT_DB') }}"      
      schema: "{{ env_var('DBT_OUTPUT_SCHEMA') }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      pass: "{{ env_var('DBT_DB_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_MAPPED_HOST_PORT') | as_number }}"      
      threads: 1
      type: postgres      
  target: dev
