services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGOPTIONS="-c max_wal_size=4GB"
    volumes:
      - "./.init_data:/var/lib/postgresql/.init_data:ro"  # csv files / simple ingestion
      - ./init-db:/docker-entrypoint-initdb.d # sql init tables
      - "./postgresql_data:/var/lib/postgresql/data:rw"   # persist dev database state   
    ports:
      - "${POSTGRES_MAPPED_HOST_PORT}:5432"
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      #build:
        #context: .  # Still the current directory
        #dockerfile: ./PgAdminDockerFile  # Specify the custom Dockerfile name
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      volumes: 
        - "./pgadmin_data:/var/lib/pgadmin:rw"
      #user: ${PGADMIN_UID}:${PGADMIN_GID}  
      depends_on:
        - pgdatabase
      ports:
        - "8888:80"